name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Shutdown existing MySQL
        run: sudo service mysql stop
        
      - name: Set up MySQL
        uses: cweinberger/github-actions-mysql@master
        with:
          version: 8.0
          hostPort: 33069
          containerPort: 3306
          rootPassword: root
          user: root
          password: root
          database: root
          characterSet: root
          collation: utf8mb4_general_ci
          sqlMode: NO_ENGINE_SUBSTITUTION
      
      - name: Setup MySQL
        run: |
          mysql -e 'DROP DATABASE IF EXISTS easyaid'
          mysql -e 'CREATE DATABASE IF NOT EXISTS easyaid;'
          mysql -u root --default-character-set=utf8 easyaid< db/EasyAid.sql
          mysql -u root --default-character-set=utf8 easyaid< db/populateDB.sql  
          
      - name: Set up JDK 16.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
