name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
        
      - name: Start Ubuntu MySQL (SUDO)
        run: sudo service mysql start
        
      - name: Setup MySQL
        run: |
          mysql -e 'DROP DATABASE IF EXISTS easyaid;' -uroot -proot
          mysql -e 'CREATE DATABASE IF NOT EXISTS easyaid;' -uroot -proot
          mysql -uroot -proot --default-character-set=utf8 easyaid< db/EasyAid.sql
          mysql -uroot -proot --default-character-set=utf8 easyaid< db/populateDB.sql  
          
      - name: Set up JDK 16.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
