name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mydb:
        image: mysql:8.0.18
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: easyaid
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
